/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:7fe4c7a4-26ed-464b-a92d-9ad4c8831c77",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_SI0DiRHnr",
    "aws_user_pools_web_client_id": "6as23uulluvufnfmlsgcatfita",
    "oauth": {}
};


export default awsmobile;
